### ISSUE TITLE
Could not find loadout file address

### ISSUE THREAD

**Issue by grufkork** [friendly-spycrab/Titanfall-2-SP-loadout-editor#1]
When I click the "Change" button a message that says "Could not find the address for the loadout file. Try entering it manually" pops up. It's followed by a text input box and an "OK" and "Exit program" button. Also, the loadout in-game isn't changed.

This error started appearing after the game crashed due to me entering an invalid weapon name, it worked fine before. I'm currently reinstalling Titanfall 2 completely (due to messing up some VPKs), I'll see if it fixes the issue.

**Comment by friendly-spycrab** [comment]
I am replacing the lookup sqlite version with a memory search version. this [tool](https://github.com/friendly-spycrab/Titanfall-2-Memory-editor) has a working memory search algorithm. so i will use that. Updating the program should take a couple of hours

**Comment by friendly-spycrab** [comment]
Should be fixed now.

**Comment by grufkork** [comment]
Ok, great!

**Comment by friendly-spycrab** [comment]
Please tell me if it is fixed

**Comment by grufkork** [comment]
It seems to be fixed! Might be because I reinstalled the game thought. I'll keep you updated if I encounter any more problems. Great work anyways!

**Comment by grufkork** [comment]
Hey BTW, could you add some info on how to change the player model in the README? Because the titan weapons models blocks the camera when using the default player model/camera location. Also, Jacks hands looks pretty creepy...

**Comment by friendly-spycrab** [comment]
this [tool](https://github.com/friendly-spycrab/Titanfall-2-Memory-editor) can do that and more
